### ISSUE TITLE
Pokemon are not fully entered into the pokedex

### ISSUE THREAD

**Issue by SteveCookTU** [SciresM/SMPatcher#2]
Not sure if there is any way to even add this feature to the patcher but if you are injecting a pokemon, it is not fully registered into the pokedex. It still needs to be either caught or traded to.

**Comment by zimlokks** [comment]
If I remember correctly from ORAS days,  putting them into the day care and out use to fix this problem.

**Comment by malicious50** [comment]
> If I remember correctly from ORAS days, putting them into the day care and out use to fix this problem.

Doing like this fix this problem also on Sun & Moon, I can confirm it.

**Comment by SciresM** [comment]
lmao

**Comment by SteveCookTU** [comment]
Closing old issues, sorry for the notifications lol
